datahub:
  created: 2017-11-09T01:27:26.384677
  findability: published
  flowid: core/geo-admin1-us/7
  hash: e13e8e69cffc10390f3b41e9be51e863
  modified: 2018-03-15T06:24:57.998294
  owner: core
  ownerid: core
  stats:
    bytes: 145589
    rowcount: 0
description: 'Natural Earth Polygons for the states in the United Stated of America'
homepage: http://github.com/datasets/geo-ne-admin1-us
id: core/geo-admin1-us
keywords:
  - geodata
  - vector
  - country
licenses:
  - type: ODC-PDDL
    url: http://opendatacommons.org/licenses/pddl/1.0/
name: geo-admin1-us
readme: |

  Geodata [data package][datapackage] providing geojson polygons for the states  \ in the USA.


  ## Data
  The data comes from [Natural Earth][naturalearth], a  \ community effort to make visually pleasing, well-crafted maps with cartography  \ or GIS software at small scale.

  This dataset covers the United States of America.  \ admin1 are the biggest administrative area below the country : ie the states.  \ See [documentation][doc] for more information.

  The shape of the admin1 have  \ four fields :
  * name : the common name for this admin1 subdivision
  * id : Natural  \ Earth ``adm1_code`` for the subdivision inside the country. [Documentation][doc]  \ is not clear what this code is, but it could be FIPS
  * code : the well known  \ two letter code for the state
  * country : name of the country
  * ISO3166-1-Alpha-3  \ : three letters iso code of the country

  [naturalearth]: http://www.naturalearthdata.com/
    [datapackage]: http://dataprotocols.org/data-packages/
  [doc]: http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/

  ## License

  All data is licensed under the [Open Data Commons Public Domain  \ Dedication and License][pddl].

  Note that the original data from [Natural Earth][naturalearth]  \ is public domain. While no credit is
  formally required a link back or credit  \ to [Natural Earth][naturalearth], [Lexman][lexman] and the [Open Knowledge Foundation][okfn]  \ is much appreciated.

  All source code is licenced under the [MIT licence][mit].

  [mit]: https://opensource.org/licenses/MIT
  [naturalearth]: http://www.naturalearthdata.com/
    [pddl]: http://opendatacommons.org/licenses/pddl/1.0/
  [lexman]: http://github.com/lexman
    [okfn]: http://okfn.org/



repository:
  type: git
  url: git://github.com/datasets/geo-ne-admin1-us.git
resources:
  - bytes: 2
    datahub:
      type: derived/report
    description: 'Validation report for tabular data'
    dpp:streamedFrom: validation_report.json
    encoding: utf-8
    format: json
    hash: d751713988987e9331980363e24189ce
    name: validation_report
    path: https://pkgstore.datahub.io/core/geo-admin1-us/validation_report/data/d751713988987e9331980363e24189ce/validation_report.json
    profile: data-resource
  - bytes: 34604
    datahub:
      type: derived/zip
    description: 'Compressed versions of dataset. Includes normalized CSV and JSON
      data with original data and datapackage.json.'
    dpp:streamedFrom: /tmp/386.geo-admin1-us.zip
    encoding: utf-8
    format: zip
    name: geo-admin1-us_zip
    path: https://pkgstore.datahub.io/core/geo-admin1-us/geo-admin1-us_zip/data/e629eafd9ab23119d5825f62b4a5aa8a/geo-admin1-us_zip.zip
    profile: data-resource
  - bytes: 110983
    datahub:
      type: original
    dpp:streamedFrom: https://s3.amazonaws.com/rawstore.datahub.io/832de13f11fc882d18d45e085758e737.geojson
    encoding: utf-8
    foreignKeys:
      - fields: ISO3166-1-Alpha-3
        reference:
          datapackage: https://github.com/datasets/country-codes/
          fields: ISO3166-1-Alpha-3
          resource: country-codes
    format: geojson
    geojsonSchema:
      fields:
        - description: 'Common name of the zone'
          name: name
          type: string
        - description: 'Code for the zone inside the country'
          name: id
          type: string
        - description: 'Name of the country'
          name: country
          type: string
        - description: '3 characters code for the country, according to ISO3166 standard'
          name: ISO3166-1-Alpha-3
          type: string
    mediatype: application/json
    name: admin1-us
    path: https://pkgstore.datahub.io/core/geo-admin1-us/admin1-us/archive/832de13f11fc882d18d45e085758e737/admin1-us.geojson
    profile: data-resource
sources:
  - name: 'Natural Earth'
    path: http://www.naturalearthdata.com/downloads/10m-cultural-vectors/10m-admin-1-states-provinces/
    title: 'Natural Earth'
title: 'Natural Earth Admin1 Polygons as GeoJSON'
version: 0.1.0
views: []


